<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<style type="text/css">
	
	.footer-logo-block{
                    width: 185px;
                    float: right;
    }
    .wyncImag{
        
                width: 26px;
          
        }
        .wync{
        	    margin-left: 52px;
        	    margin-top: 3px;
        }
    .twitter{
            float:right;
            width:auto;
            margin-right:5px;
        }
         .twiImag{
                width: 26px;
            }
	.facebook{
	    width:35px;
	    float: right;
	    
    }
    .fbImag{
	        width: 11px;
	    }
</style>
<small class="copyright">
<hr class=footerHr>
    <span><?php /* @escapeNotVerified */ echo $block->getCopyright() ?></span>
    <div class="footer-logo-block">
    
    	
    	<div class="flogo twitter"><a href=""><img class="twiImage" src="<?php echo $block->getViewFileUrl('images/home/twt.png'); ?>"/></a></div>
    	<div class="flogo facebook"><a href=""><img class="fbImag" src="<?php echo $block->getViewFileUrl('images/home/fb.png');?>"/></a></div>
    	<div class="flogo wync"><a href=""><img class="wyncImag" src="<?php echo $block->getViewFileUrl('images/home/vk.png'); ?>"/></a></div>
    	
    </div>
    <div style="clear:both"></div>
</small>