<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="footer-container">
    <div class="footer">
    <div  class="footer links">
    	<div>
	    	NAVIGATION
	    </div>


		<ul class="footer links">
		    <li class="nav item"><a href="{{store url="about-us"}}">About us</a></li>
		    <li class="nav item"><a href="{{store url="customer-service"}}">Customer Service</a></li>
		    <li class="nav item"><a href="{{store url="about-us"}}">About us</a></li>
		    <li class="nav item"><a href="{{store url="customer-service"}}">Customer Service</a></li>
		    <li class="nav item"><a href="{{store url="about-us"}}">About us</a></li>
		    <li class="nav item"><a href="{{store url="customer-service"}}">Customer Service</a></li>
		</ul>
    </div>
    <div  class="footer links">
    	<div>MORE</div>
		<ul>
		    <li class="nav item"><a href="{{store url="about-us"}}">About us</a></li>
		    <li class="nav item"><a href="{{store url="customer-service"}}">Customer Service</a></li>
		    <li class="nav item"><a href="{{store url="about-us"}}">About us</a></li>
		    <li class="nav item"><a href="{{store url="customer-service"}}">Customer Service</a></li>
		    <li class="nav item"><a href="{{store url="about-us"}}">About us</a></li>
		    <li class="nav item"><a href="{{store url="customer-service"}}">Customer Service</a></li>
		</ul>
    </div>
	    
		
    </div>
</div>
