<style>
	.cms-index-index .page-main{
		max-width:100%;
		padding: 0;
		
	}
	.column.main{
		padding-bottom: 0 !important;
	}
	.panel.header,
	nav.navigation{
		max-width: 1060px !important;
    margin: 0 auto !important;
    padding-left: 0 !important;
    padding-right: 0 !important;
	}
	.main_Border{
		width: 1060px;
    	margin: 0px auto;
	}
	.home-middle-container{
		width: 1060px;
    	margin: 0px auto;
	}
	.home-top-banner{
		background: url('https://otentikaweb.com/pub/static/frontend/otentika/view/en_US/images/home/banners/gradient.png');
		    background-repeat: repeat-x;
    background-position: 0 390px;
	}
	.home-bottom-container{
		background:#f9f9f9;
		padding: 85px 0;
	}
	.cms-index-index .product-bottom-banner-container{
		margin: 0 !important;
	}
	.home-bottom-container-content{width: 1060px;
    	margin: 0px auto;}
    .column.main .main_Border{
    	border: 12px solid #eb966d;
    	border-bottom: 0;
    	position: relative;
    	max-height: 450px;
    }
    .main_Border .ethenic{
    	position: absolute;
    	left: 12%;
    	top: 25%;
    	padding: 0 !important;
    }
    .product-bottom-banner-container{
    	background: #fff;
    	padding-bottom: 0;
    }
    .product-bottom-banner-container .left-banner{
    	width: 25%;
    	padding-bottom: 0 !important;
    }
    .product-bottom-banner{
    	padding: 0 !important;
    }
    .product-bottom-banner-container .right-banner{
    	width: 72%;
    }
    .main-first-left{
    	background: #f9f9f9;
    	float: left;
    	width: 215px;

    }
    .main-first-right{
    	float: right;
    	background: #f9f9f9;
    	width: calc(100% - 40px - 215px) !important;
    	margin-left: 40px;
    }
    button{
    	text-transform: uppercase;
    	border-radius: 0;
    }
    h1{
    	font-size: 21px;
    	font-weight: 600;
    }
    .baner2_title{
    	    width: 140px;
    margin: 55px auto 25px;
    line-height: 30px;
    text-align: center;
    }
    hr{
    	border-top: 2px solid #f95318;
    box-shadow: none;
    
    }
    .banner2_hr{
    	width: 40px;
    }
    .banner2_descrp{
    	    width: 160px;
	    text-align: center;
	    margin: 0 auto;
	    color: #878787;
    }
    .banner2_img{
    	width: 160px;
    margin: 25px 27.5px -5px;
    text-align: center;
    }
    .banner3Body{
    	height: 379px;
    }
    .banner3_div{
    	max-width: 350px;
    	float: left;
    }
    .banner3_share_icn{
    	float: right;
    	height: 100%;
    }
    .banner3_share_icn img{
    	height: 100%;
    }
    .banner7 {
    width: 99.5%;
    background: #f95318;
    float: left;
    padding: 0px 2px;
    height: 289px;
    margin-bottom: 96px;
    margin-top: 20px;
}

.banner7 .banner7image {
    height: 289px;
    margin-left: 4%;
}

.banner7 .banner7emnt {
    float: right;
    padding: 7% 11%;
    color: #ffffff;
}

.banner7 .banner7emnt h1 {
    font-weight: 400;
    margin: -31px 0px 36px -2px;
}

.banner7 .banner7emnt span {
    font-size: 12px;
}

.banner7 .banner7btn {
    margin-top: 20px;
}

.banner7 .banner7btn .action.tocart.primary {
    border: 1px solid;
    border-radius: 0;
    border: 1px solid #fa865c;
}
.banner3image {
  padding: 23px 0px 0px;
  position: relative;
}
.banner3image .imgb3Detail {
      font-size: 12px;
    color: #878787;
    text-align: center;
    padding-top: 135px;
}
.banner3image .imgb3 {
  height: 193px;
  padding-bottom: 18px;
  position: relative;
}
.main-second {
	margin-top: 35px;
}
.main-second-left{
	float: left;
}
.main-second-middle {
	float: left;
}
.main-second-right{
	float: right;
}
.main-second-left-top,
.main-second-left-bottom{
	width: 215px;
}
.main-second-left-bottom{
	margin-top: 35px;
}
.banner3image{
	background: url('https://otentikaweb.com/pub/media/wysiwyg/b3.png');
	    height: 170px;
    padding: 0;
    background-size: contain;
}
.banner4image{
	background: url('https://otentikaweb.com/pub/media/wysiwyg/b4.png') no-repeat;
	    height: 170px;
    padding: 0;
    background-size: contain;
    text-align: center;
}
.banner4image h1{
	    margin-bottom: 5px;
    line-height: 25px;
    font-size: 21px;
}
.banner4imageDtls1{
	padding-top: 35px;
}
.main-second-middle{
	width: calc(100% - 100px - 355px) !important;
	margin-left: 35px;
}
.main-second-middle-content{
	background: url(https://otentikaweb.com/pub/media/wysiwyg/b5.png) no-repeat;
    height: 338px;
    padding: 0;
    background-size: contain;
    background-position: center right;
    background-color: #f5f5f5;
    padding-top: 30px;

}
.main-second-right{
	margin-left: 35px;
}
.main-second-right-content{
	background: url(https://otentikaweb.com/pub/media/wysiwyg/b6.png) no-repeat;
    height: 323px;
    background-size: contain;
    padding: 45px 15px 0;
    width: 140px;
    background-position: center;
    background-color: #f5f5f5;
}
.banner6dt1 h1{
	margin-bottom: 20px;
}
.banner6dt2{
	margin-top: 200px;
    color: #878787;
}
.banner4imageDtls2,
.banner3_discrp_right p,
.banner5dt2,
.banner3_discrp_right{
	color: #878787;
}
.banner3_discrp_right{
	margin-top: 25px;
}
.banner3_title{
	       margin: 55px 25px 25px;
    width: 254px;
    text-align: left;
}
.banner3_title h1{
	    width: 120px;
    line-height: 30px;
    margin-bottom: 25px;
}
.banner3_title hr{
	width: 40px;
    margin: 0;
}
.banner3_elmnt {
	margin-top: 100px;
}
.bannerImg5Dtls{
	    background: black;
    border-radius: 50px;
    color: white;
    font-size: 33px;
    width: 86px;
    height: 86px;
    margin-left: 30px;
}
.banner5dt1,
.banner5dt2{
	margin-left: 30px;
}
.banner5dt1{
	margin-top: 125px;
}
.banner5dt1 h1{
	margin-bottom: 5px;
	line-height: 25px;
}
.bannerImg5Dtls span{
	    margin: 22px;
    line-height: 86px;
}
.banner3_discrp_right,
.banner3_elmnt{
	margin-left: 25px;
}
.banner3_hr_right{
	width: 40px;
	margin: 0;
	margin-left: 25px;
}
.banner3_img{
	margin-left: 25px;
}
</style>
<div class="home-top-banner">
	<div class="main_Border"><img class="banner1" src="<?php echo $block->getViewFileUrl('images/home/banners/girlHome.png'); ?>" alt="" />
	<div class="ethenic">
		<h1 class="ethenic_title">ETHNIC BEAUTY</h1>
		<button class="action tocart primary" title="Add to Cart" type="submit"> <span class="shop_btn">Shop Now</span> </button></div>
	</div>
</div>
<div class="home-middle-container">
	<div class="middle-main">
		<div class="main-first">
			<div class="main-first-left">
				<div class="banner2_elmnt">
					<h1 class="baner2_title">NEW FORMULA</h1>
					<hr class="banner2_hr">
					<p class="banner2_descrp">More that two decades in the making</p>
					<img class="banner2_img" src="<?php echo $block->getViewFileUrl('images/home/banners/bottle.png'); ?>" alt="">
				</div>
			</div>
			<div class="main-first-right">
				<div class="banner3Body">
				    <div class="banner3_div">
				        <h1 class="banner3_title">
				            LET YOUR SKIN GLOW
				        </h1>
				        <hr class="banner3_hr_right">
				            <p class="banner3_discrp_right">
				                Rejurvenate your skin at discount of over 30% on new O'Tentika products
				            </p>
				            <div class="banner3_elmnt">
				                <button onclick="window.location.href='<?php echo $block->getUrl('products.html') ?>'" class="action tocart primary">
				                    Products
				                </button>
				                <a class="banner3_btn" href="#">
				                    <img alt="" class="banner3_img" src="https://otentikaweb.com/pub/media/wysiwyg/share.png">
				                    </img>
				                </a>
				            </div>
				        </hr>
				    </div>
				    <div class="banner3_share_icn">
				        <img alt="" src="https://otentikaweb.com/pub/media/wysiwyg/bg.png">
				        </img>
				    </div>
				</div>
			</div>
			<div style="clear: both;"></div>
		</div>

		<div class="main-second">
			<div class="main-second-left">
				<div class="main-second-left-top">
					<div class="banner3image">
				        <div class="imgb3Detail">
				            <span>
				                56 Products
				            </span>
				        </div>
					</div>
				</div>
				<div class="main-second-left-bottom">
					<div class="banner4image">
				        <div class="banner4imageDtls1">
				            <h1>
				                NEW YORK
				                <br>
				                    EXCLUSIVE
				                </br>
				            </h1>
				        </div>
				        <div class="banner4imageDtls2">
				            <span>
				                Beneficial only today
				            </span>
				        </div>
					</div>
				</div>
			</div>
			<div class="main-second-middle">
				<div class="main-second-middle-content">
			        <div class="bannerImg5Round">
			        </div>
			        <div class="bannerImg5Dtls">
			            <span>
			                70
			                <small>
			                    %
			                </small>
			            </span>
			        </div>
			        <div class="banner5dt1">
			            <h1>
			                DISCOUNTS
			                <br>
			                    FOR MEN
			                </br>
			            </h1>
			        </div>
			        <div class="banner5dt2">
			            <span>
			                Only until 1 December
			            </span>
			        </div>
				</div>
			</div>
			<div class="main-second-right">
				<div class="main-second-right-content">
			        <div class="banner6dt1">
			            <h1>
			                BRIGHTENING
			                <br>
			                    SKIN MILK
			                </br>
			            </h1>
			            <hr/>
			        </div>
			        <div class="banner6dt2">
			            <span>
			                from $ 35
			            </span>
			        </div>
				</div>
			</div>
			<div style="clear: both;"></div>
		</div>

		<div class="main-third">
			<div class="banner7">
			    <img alt="" class="banner7image" src="https://otentikaweb.com/pub/media/wysiwyg/banner6.png">
			        <div class="banner7emnt">
			            <h1>
			                CLEAN &amp; HEALTHY SKIN
			            </h1>
			            <span>
			                An original formula for dry skin that comes in milk or cream to brighten and smoothen your
			                <br>
			                    skin. It restores a radiant beauty from ashy skin and reduces the appearance of dark spots
			                    <br>
			                        and blemishes.Improved moisturiziung effect to better suit dry skin.
			                    </br>
			                </br>
			            </span>
			            <div class="banner7btn">
			                <button class="action tocart primary" title="Add to Cart" type="submit">
			                    <span class="shop_btn">
			                        ADD TO CART
			                    </span>
			                </button>
			            </div>
			        </div>
			    </img>
			</div>
		</div>
	</div>
</div>
<div style="clear: both;"></div>
<div class="home-bottom-container">
	<div class="home-bottom-container-content">
	<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('product_bottom_banner')->toHtml(); ?>
	</div>
</div>
