
<div class="home-top-banner">
	<div class="main_Border"><img class="banner1" src="<?php echo $block->getViewFileUrl('images/home/banners/girlHome.png'); ?>" alt="" />
	<div class="ethenic">
		<h1 class="ethenic_title">ETHNIC BEAUTY</h1>
		<button class="action tocart primary" title="Add to Cart" type="submit"> <span onclick="window.location.href= '<?php echo $block->getUrl('products.html'); ?>'" class="shop_btn">Shop Now</span> </button></div>
	</div>
</div>
<div class="home-middle-container">
	<div class="middle-main">
		<div class="main-first">
			<div class="main-first-left">
				<div class="banner2_elmnt">
					<h1 class="baner2_title">NEW FORMULA</h1>
					<hr class="banner2_hr">
					<p class="banner2_descrp">More that two decades in the making</p>
					<img class="banner2_img" src="<?php echo $block->getViewFileUrl('images/home/banners/bottle.png'); ?>" alt="">
				</div>
			</div>
			<div class="main-first-right">
				<div class="banner3Body">
				    <div class="banner3_div">
				        <h1 class="banner3_title">
				            LET YOUR <br>SKIN GLOW
				        </h1>
				        <hr class="banner3_hr_right">
				            <p class="banner3_discrp_right">
				                Rejurvenate your skin at discount of over 30% on new O'Tentika products
				            </p>
				            <div class="banner3_elmnt">
				            	<div class="button">
				            		<a href="<?php echo $block->getUrl('products.html'); ?>">Products</a>
				            		<!-- <button class="action tocart primary">
					                    Products
					                </button> -->
				            	</div>
								<div class="share">
									<a class="banner3_btn" href="#">
										<img alt="" class="banner3_img" src="https://otentikaweb.com/pub/media/wysiwyg/share.png" />
									</a>
								</div>
					                
				            </div>
				        </hr>
				    </div>
				    <!-- <div class="banner3_share_icn">
				        <img alt="" src="https://otentikaweb.com/pub/media/wysiwyg/bg.png">
				        </img>
				    </div> -->
				</div>
			</div>
			<div style="clear: both;"></div>
		</div>
		<div style="clear: both;"></div>
		<div class="main-second">
			<div class="main-second-left">
				<div class="main-second-left-top">
					<div class="banner3image">
				        <div class="imgb3Detail">
				            <span>
				                56 Products
				            </span>
				        </div>
					</div>
				</div>
				<div class="main-second-left-bottom">
					<div class="banner4image">
				        <div class="banner4imageDtls1">
				            <h1>
				                NEW YORK
				                <br>
				                    EXCLUSIVE
				                </br>
				            </h1>
				        </div>
				        <div class="banner4imageDtls2">
				            <span>
				                Beneficial only today
				            </span>
				        </div>
					</div>
				</div>
			</div>
			<div class="main-second-middle">
				<div class="main-second-middle-content">
			        <div class="bannerImg5Round">
			        </div>
			        <div class="bannerImg5Dtls">
			            <span>
			                70
			                <sup>
			                    %
			                </sup>
			            </span>
			        </div>
			        <div class="banner5dt1">
			            <h1>
			                DISCOUNTS
			                <br>
			                    FOR MEN
			                </br>
			            </h1>
			        </div>
			        <div class="banner5dt2">
			            <span>
			                Only until 1 December
			            </span>
			        </div>
				</div>
			</div>
			<div class="main-second-right">
				<div class="main-second-right-content">
			        <div class="banner6dt1">
			            <h1>
			                BRIGHTENING
			                <br>
			                    SKIN MILK
			                </br>
			            </h1>
			            <hr/>
			        </div>
			        <div class="banner6dt2">
			            <span>
			                from $ 35
			            </span>
			        </div>
				</div>
			</div>
			<div style="clear: both;"></div>
		</div>
		<div style="clear: both;"></div>
		<div class="main-third">
			<div class="banner7">
			    <img alt="" class="banner7image" src="https://otentikaweb.com/pub/media/wysiwyg/banner6.png">
			        <div class="banner7emnt">
			            <h1>
			                CLEAN &amp; HEALTHY SKIN
			            </h1>
			            <span>
			                An original formula for dry skin that comes in milk or cream to brighten and smoothen your
			                <br>
			                    skin. It restores a radiant beauty from ashy skin and reduces the appearance of dark spots
			                    <br>
			                        and blemishes.Improved moisturiziung effect to better suit dry skin.
			                    </br>
			                </br>
			            </span>
			            <div class="banner7btn">
			                <button class="action tocart primary" title="Add to Cart" type="submit">
			                    <span class="shop_btn">
			                        ADD TO CART
			                    </span>
			                </button>
			            </div>
			        </div>
			    </img>
			</div>
		</div>
	</div>
</div>
<div style="clear: both;"></div>
<div class="home-bottom-container">
	<div class="home-bottom-container-content">
	<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('product_bottom_banner')->toHtml(); ?>
	</div>
</div>
