<div class="main-banner">
	<div class="main-banner-content">
		<div class="main-text">
			<h1>Black Friday Sale</h1>
		</div>
		<div class="dots">
			<div></div>
			<div></div>
			<div></div>
		</div>
		<div class="offer">
			<h3>-&nbsp;45% Off</h3>
		</div>
		<div class="button">
			<a href="#" class="">Shop Now</a>
		</div>
	</div>
</div>
<div class="top-banner">
	<div class="top-banner-content">
		<div class="left-banner">
			<h4 class="heading">New Product Line</h4>
			<h1 class="main-heading">Pure<br>Nature</h1>
			<div class="desc">
				<span>Infused with kiwi extract<br>gives radiant beauty to dark skin</span>
			</div>
		</div>
		<div class="right-banner">
			<div class="day-num"><img src="<?php echo $block->getViewFileUrl('images/special/7.png'); ?>"></div>
		</div>
	</div>
</div>
<div style="clear: both;"></div>
<div class="middle-banner">
	<div class="middle-banner-content">
		<div class="left-banner">
			<div class="left-banner-content">
				<h1 class="heading">
					We give back to the people
				</h1>
				<div class="text">
					<span>Why we raised our quality while dropping the prices</span>
				</div>
			</div>
		</div>
		<div class="right-banner">
			<div class="right-banner-content">
				<h1 class="heading">Green is the new black.<br>Seriously.</h1>
				<div class="date">Sep 18, 2016</div>
				<div class="dots">
					<div></div>
					<div></div>
					<div></div>
				</div>
				<div class="text">
					Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.
					<a class="read-more" href="#">Read More</a>
				</div>
			</div>
		</div>
	</div>
		
</div>
<div style="clear: both;"></div>
<div class="bottom-banner">
	<div class="bottom-banner-content">
		<div class="left-banner banner-div">
			<div class="background"></div>
			<div class="star-div">
				<div class="star"><img src="<?php echo $block->getViewFileUrl('images/special/star.png'); ?>"></div>
			</div>
			<div class="content">
				<div class="heading">Winter Skin Treatment</div>
				<div class="text">O'Tentika Blog</div>
			</div>
				
		</div>
		<div class="middle-banner banner-div">
			<div class="background"></div>
			<div class="middle-banner-content">
				<div class="top">
					<h3>Hand<br>Cream</h3>
					<h2>Sale</h2>
				</div>
				<div class="bottom">
					<div class="offer"><span class="amt">50</span><sup>%</sup><span class="label">off</span></div>
				</div>
			</div>
		</div>
		<div class="right-banner banner-div">
			<div class="heading"><span>Season Sale</span></div>
			<div class="content">
				<h2>The holiday Begins!</h2>
				<div class="text">Only until December 30, Have time to order!</div>
			</div>
			<div class="button">
				<a href="#" class="">Shop Now</a>
			</div>
		</div>
	</div>
</div>
<div style="clear: both;"></div>