<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Top menu for store
 *
 * @var $block \Magento\Theme\Block\Html\Topmenu
 */
$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();
$appState = $objectManager->get('\Magento\Framework\App\State');
$logo = $objectManager->get('\Magento\Theme\Block\Html\Header\Logo');
$homeUrl = 'javascript:void(0)';
if(!($logo->isHomePage())){
    $homeUrl = $block->getUrl('');
}
?>

<?php $columnsLimit = $block->getColumnsLimit() ?: 0; ?>
<?php $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit) ?>

<nav class="navigation" data-action="navigation">
    <ul data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>

        <li class="level0 nav-1 first level-top ui-menu-item mobile-menu-home-link" role="presentation">
            <a href="<?php echo $homeUrl; ?>" class="level-top ui-corner-all" tabindex="-1" role="menuitem">
                <span><?php echo __('Home') ?></span>
            </a>
        </li>

        <li class="level0 nav-1 first level-top ui-menu-item menu-logo" role="presentation">
            <a href="<?php echo $homeUrl; ?>" class="level-top ui-corner-all" tabindex="-1" role="menuitem">
                <span>
                    <img src="<?php /* @escapeNotVerified */ echo $logo->getLogoSrc() ?>"
                     alt="<?php /* @escapeNotVerified */ echo $logo->getLogoAlt() ?>"
                     <?php echo $logo->getLogoWidth() ? 'width="' . $logo->getLogoWidth() . '"' : '' ?>
                     <?php echo $logo->getLogoHeight() ? 'height="' . $logo->getLogoHeight() . '"' : '' ?>
                    />
                </span>
            </a>
        </li>
        <li class="level0 nav-1 first level-top ui-menu-item" role="presentation">
            <a href="<?php echo $block->getUrl('about-us'); ?>" class="level-top ui-corner-all" tabindex="-1" role="menuitem">
                <span><?php echo __("The Brand"); ?></span>
            </a>
        </li>
        <?php /* @escapeNotVerified */ echo $_menu; ?>
        <?php /* @escapeNotVerified */ echo $block->getChildHtml(); ?>
        <li class="level0 nav-1 first level-top ui-menu-item" role="presentation">
            <a href="<?php echo $block->getUrl('what-is-new'); ?>" class="level-top ui-corner-all" tabindex="-1" role="menuitem">
                <span><?php echo __("What's New"); ?></span>
            </a>
        </li>
        <li class="level0 nav-1 first level-top ui-menu-item" role="presentation">
            <a href="<?php echo $block->getUrl('contact'); ?>" class="level-top ui-corner-all" tabindex="-1" role="menuitem">
                <span><?php echo __("Contact Us"); ?></span>
            </a>
        </li>
        
    </ul>
</nav>
