<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<?php
/** @var $block \Magento\Framework\View\Element\Template */
/** @var $helper \Magento\Search\Helper\Data */
$helper = $this->helper('Magento\Search\Helper\Data');
?>
<div class="minicart-search">
     <div data-block="minicart" class="minicart-wrapper">
      <a class="action showcart" href="<?php /* @escapeNotVerified */ echo $block->getShoppingCartUrl(); ?>"
         data-bind="scope: 'minicart_content'">
          <span class="text"><?php /* @escapeNotVerified */ echo __('My Cart'); ?></span>
          <span class="counter qty empty"
                data-bind="css: { empty: !!getCartParam('summary_count') == false }, blockLoader: isLoading">
              <span class="counter-number"><!-- ko text: getCartParam('summary_count') --><!-- /ko --></span>
              <span class="counter-label">
              <!-- ko if: getCartParam('summary_count') -->
                  <!-- ko text: getCartParam('summary_count') --><!-- /ko -->
                  <!-- ko i18n: 'items' --><!-- /ko -->
              <!-- /ko -->
              </span>
          </span>
      </a>
      <?php if ($block->getIsNeedToDisplaySideBar()): ?>
          <div class="block block-minicart empty"
               data-role="dropdownDialog"
               data-mage-init='{"dropdownDialog":{
                  "appendTo":"[data-block=minicart]",
                  "triggerTarget":".showcart",
                  "timeout": "2000",
                  "closeOnMouseLeave": false,
                  "closeOnEscape": true,
                  "triggerClass":"active",
                  "parentClass":"active",
                  "buttons":[]}}'>
              <div id="minicart-content-wrapper" data-bind="scope: 'minicart_content'">
                  <!-- ko template: getTemplate() --><!-- /ko -->
              </div>
              <?php echo $block->getChildHtml('minicart.addons'); ?>
          </div>
      <?php endif ?>
      <script>
          window.checkout = <?php /* @escapeNotVerified */ echo \Zend_Json::encode($block->getConfig()); ?>;
      </script>
      <script type="text/x-magento-init">
      {
          "[data-block='minicart']": {
              "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout();?>
          },
          "*": {
              "Magento_Ui/js/block-loader": "<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/loader-1.gif'); ?>"
          }
      }
      </script>
  </div>
  <li class="link wishlist" data-bind="scope: 'wishlist'">
              <a href="<?php /* @escapeNotVerified */ echo $block->getUrl('wishlist') ?>">
              <img src="<?php echo $block->getViewFileUrl('images/home/wishlist.png'); ?>">
              </a>
          </li>
          <script type="text/x-magento-init">
              {
                  "*": {
                      "Magento_Ui/js/core/app": {
                          "components": {
                              "wishlist": {
                                  "component": "Magento_Wishlist/js/view/wishlist"
                              }
                          }
                      }
                  }
              }

          </script>
 


  <div class="block block-search">
      <div class="block block-title"><strong><?php /* @escapeNotVerified */ echo __('Search'); ?></strong></div>
      <div class="block block-content">
          <form class="form minisearch" id="search_mini_form" action="<?php /* @escapeNotVerified */ echo $helper->getResultUrl() ?>" method="get">
              <div class="field search">
                  <label class="label" for="search" data-role="minisearch-label">
                      <span><?php /* @escapeNotVerified */ echo __('Search'); ?></span>
                  </label>
                  <div class="control">
                      <input id="search"
                             data-mage-init='{"quickSearch":{
                                  "formSelector":"#search_mini_form",
                                  "url":"<?php /* @escapeNotVerified */ echo $block->getUrl('search/ajax/suggest', ['_secure' => $block->getRequest()->isSecure()]); ?>",
                                  "destinationSelector":"#search_autocomplete"}
                             }'
                             type="text"
                             name="<?php /* @escapeNotVerified */ echo $helper->getQueryParamName() ?>"
                             value="<?php /* @escapeNotVerified */ echo $helper->getEscapedQueryText() ?>"
                             class="input-text"
                             maxlength="<?php /* @escapeNotVerified */ echo $helper->getMaxQueryLength();?>"
                             role="combobox"
                             aria-haspopup="false"
                             aria-autocomplete="both"
                             autocomplete="off"/>
                      <div id="search_autocomplete" class="search-autocomplete"></div>
                      <?php echo $block->getChildHtml() ?>
                  </div>
              </div>
              <div class="actions">
                  <button type="submit"
                          title="<?php echo $block->escapeHtml(__('Search')) ?>"
                          class="action search">
                      <span><?php /* @escapeNotVerified */ echo __('Search'); ?></span>
                  </button>
              </div>
          </form>
      </div>
  </div>

</div>

