<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 *
 * @var $block \Magento\Customer\Block\Account\Forgotpassword
 */

// @codingStandardsIgnoreFile

?>

<div class="field note title">
<div class="loginTitle"><span><?php echo __('GLAD TO SEE YOU BACK :)') ?></span></div>
    <div class="text">
        <div class="link-container" id="leftContainer">
            <a href="<?php echo $block->getUrl('customer/account/create') ?>"><?php echo __("I don't have an account") ?></a>
        </div>
        <div class="link-container divider"></div>
        <div class="link-container" id="rightContainer">
            <a href="<?php echo $block->getForgotPasswordUrl(); ?>"><?php echo __("I forgot my password") ?></a>
        </div>
    </div>
    
</div>
<div style="clear: both">
</div>

<form class="form password forget"
      action="<?php /* @escapeNotVerified */ echo $block->getUrl('*/*/forgotpasswordpost') ?>"
      method="post"
      id="form-validate"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
        <div class="field note">
            <h2><?php echo __('Keep Calm and Reset') ?></h2>
            <div class="text assistance"><?php /* @escapeNotVerified */ echo __("Forgot your password? We'll send you a temporary one.")." ".__("For your security, we'll also delete any saved payment info."); ?></div>
            <div class="text assistance"><?php /* @escapeNotVerified */ echo __('If you need assistance, please call Customer Service at 1-800-800-8000 and we will help you set a new password.'); ?></div>
        </div>
        <div class="field email required">
            <!-- <label for="email_address" class="label"><span><?php /* @escapeNotVerified */ echo __('Email') ?></span></label> -->
            <div class="control">
                <input placeholder="<?php echo "* ".__('EMAIL ADDRESS') ?>" type="email" name="email" alt="email" id="email_address" class="input-text" value="<?php echo $block->escapeHtml($block->getEmailValue()) ?>" data-validate="{required:true, 'validate-email':true}">
            </div>
        </div>
        <?php echo $block->getChildHtml('form_additional_info'); ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action submit primary"><span><?php /* @escapeNotVerified */ echo __('Submit') ?></span></button>
        </div>
        <div class="secondary">
            <a class="action back" href="<?php /* @escapeNotVerified */ echo $block->getLoginUrl() ?>"><span><?php /* @escapeNotVerified */ echo __('Go back') ?></span></a>
        </div>
    </div>
</form>


<style type="text/css">
    .loginTitle span{
        font-size: 26px;
    font-weight: 300;
    margin-bottom: 22px
    }
    .link-container a{
            font-size: 20px;
            color: #575757;
            font-weight: 300;
            text-decoration: underline #000;
    }
    .field.note .title{
         margin: 0px auto;
        width: 58%;
    }
     .field.note .text{
  
    margin: 0px auto;
    width: 35%;
    }

   #leftContainer{
        display: inline-block;
        float: left !important;
    }
    #rightContainer{
       float: right !important;
    }
    .link-container .divider{
        height: 20px !important;
    border-right: 1.5px solid rgba(119, 119, 119, 0.7) !important;
    margin: 9px 35px !important;
    float: left !important;
    }
    .form.password.forget{
            min-width: 600px;
    width: 70%;
    }

    .field.note .text.assistance{
  
    margin: 0px auto;
    width: 65%;
    }

    .field.email.required{
            margin: 0px auto;
    width: 64%;
    }

    .loginTitle{
            width: 46%;
    margin: 0px auto;
    margin-bottom: 26px;
    }

    #email_address::-webkit-input-placeholder {
    color: black;
    font-weight: 600;
    font-size: 19px;
    }
    #email_address{
            height: 52px !important;
    border: 2px solid lightgray;
    }
</style>