<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 *
 * @var $block \Magento\Customer\Block\Account\Forgotpassword
 */

// @codingStandardsIgnoreFile

?>
<form class="form password forget"
      action="<?php /* @escapeNotVerified */ echo $block->getUrl('*/*/forgotpasswordpost') ?>"
      method="post"
      id="form-validate"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
        <div class="field note">
            <h2><?php echo __('Keep Calm and Reset') ?></h2>
            <div class="text"><?php /* @escapeNotVerified */ echo __("Forgot your password? We'll send you a temporary one.")." ".__("For your security, we'll also delete any saved payment info."); ?></div>
            <div class="text assistance"><?php /* @escapeNotVerified */ echo __('If you need assistance, please call Customer Service at 1-800-800-8000 and we will help you set a new password.'); ?></div>
        </div>
        <div class="field email required">
            <!-- <label for="email_address" class="label"><span><?php /* @escapeNotVerified */ echo __('Email') ?></span></label> -->
            <div class="control">
                <input placeholder="<?php echo "* ".__('EMAIL ADDRESS') ?>" type="email" name="email" alt="email" id="email_address" class="input-text" value="<?php echo $block->escapeHtml($block->getEmailValue()) ?>" data-validate="{required:true, 'validate-email':true}">
            </div>
        </div>
        <?php echo $block->getChildHtml('form_additional_info'); ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action submit primary"><span><?php /* @escapeNotVerified */ echo __('Submit') ?></span></button>
        </div>
        <div class="secondary">
            <a class="action back" href="<?php /* @escapeNotVerified */ echo $block->getLoginUrl() ?>"><span><?php /* @escapeNotVerified */ echo __('Go back') ?></span></a>
        </div>
    </div>
</form>
