<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
USAGE:

Simple:

<?php echo $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Dob')
   ->setDate($block->getCustomer()->getDob())
   ->toHtml() ?>

For checkout/onepage/billing.phtml:

<?php echo $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Dob')
   ->setDate($block->getCustomer()->getDob())
   ->setFieldIdFormat('billing:%s')
   ->setFieldNameFormat('billing[%s]')
   ->toHtml() ?>

NOTE: Regarding styles - if we leave it this way, we'll move it to boxes.css
      Alternatively we could calculate widths automatically using block input parameters.
*/

/**
 * @see \Magento\Customer\Block\Widget\Dob
 */
?>
<?php
  $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
  $customerSession = $objectManager->get('Magento\Customer\Model\Session');
  $dob = null;
  if($customerSession->isLoggedIn()) {
    $date = new \DateTime($customerSession->getCustomer()->getDob());
    $dob = $date->format('m/d/Y');
    // echo $date->format('m/d/Y');
  }
  
?>
<?php
$fieldCssClass = 'field date field-' . $block->getHtmlId();
$fieldCssClass .= $block->isRequired() ? ' required' : '';
?>
<div class="<?php /* @escapeNotVerified */ echo $fieldCssClass; ?>">
    <label class="label" for="<?php echo $block->getHtmlId()?>"><span><?php echo __('BIRTHDATE'); /* @escapeNotVerified */ //echo $block->getLabel() ?></span></label>
    <div class="control customer-dob">
    <!-- <span class="titleBirthDay">BIRTHDATE</span> -->
        <?php //echo $block->getFieldHtml(); ?>
        <input value="<?php echo $dob ?>" type="text" name="dob" id="dob_custom" placeholder="MM/DD/YYYY" readonly="true">
        <?php if ($_message = $block->getAdditionalDescription()) : ?>
            <div class="note"><?php /* @escapeNotVerified */ echo $_message; ?></div>
        <?php endif; ?>
    </div>
</div>

<script>
require([
    'jquery',
    'mage/calendar'
], function($){

    $( "#dob_custom" ).calendar({
      changeMonth: true,
      changeYear: true,
      yearRange: "-100:+0"
    });

});
</script>