<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<div class="block newsletter">
    <h2>Et mi eget ornare.</h2>
    <h4>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus gravida et mi eget ornare. In ultrices velit ac elementum sagittis. </h4>
    <div class="title"><strong>free subscription</strong></div>
    <div class="content">
        <form class="form subscribe"
            novalidate
            action="<?php /* @escapeNotVerified */ echo $block->getFormActionUrl() ?>"
            method="post"
            data-mage-init='{"validation": {"errorClass": "mage-error"}}'
            id="newsletter-validate-detail">

            <div class="field newsletter">
               
                <div class="control">
                    <input name="email" type="email" id="newsletter"
                                data-validate="{required:true, 'validate-email':true}"/>
                </div>
            </div>
            <div class="actions">
                <button class="action subscribe primary" title="<?php /* @escapeNotVerified */ echo __('Subscribe') ?>" type="submit">
                    <span><?php /* @escapeNotVerified */ echo __('Subscribe') ?></span>
                </button>
            </div>
        </form>
    </div>
</div>
