<?php
/**
 * Top menu for store
 *
 * @var $block \Magento\Theme\Block\Html\Topmenu
 */
$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();
$appState = $objectManager->get('\Magento\Framework\App\State');
$logo = $objectManager->get('\Magento\Theme\Block\Html\Header\Logo');
$homeUrl = 'javascript:void(0)';
if(!($logo->isHomePage())){
    $homeUrl = $block->getUrl('');
}
?>
<?php $columnsLimit = $block->getColumnsLimit() ? : 0; ?>
<?php $_menu2 = $block->getHtml('level-top', 'mega', $columnsLimit) ?>
<?php $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit) ?>
<?php if ($block->allowExtension()): ?>
    <script>

        require([
            'jquery',
            'ibnabmodernizr'
        ], function ($) {


            $('.menu > ul > li:has( > ul)').addClass('menu-dropdown-icon');
            //Checks if li has sub (ul) and adds class for toggle icon - just an UI


            $('.menu > ul > li > ul:not(:has(ul))').addClass('normal-sub');
            //Checks if drodown menu's li elements have anothere level (ul), if not the dropdown is shown as regular dropdown, not a mega menu (thanks Luka Kladaric)

            $(".menu > ul").before("<a href=\"#\" class=\"menu-mobile\">Navigation</a>");

            //Adds menu-mobile class (for mobile toggle menu) before the normal menu
            //Mobile menu is hidden if width is more then 959px, but normal menu is displayed
            //Normal menu is hidden if width is below 959px, and jquery adds mobile menu
            //Done this way so it can be used with wordpress without any trouble

            $(".menu > ul > li").hover(function (e) {
                if ($(window).width() > 943) {
                    $(this).children("ul").stop(true, false).fadeToggle(150);
                    e.preventDefault();
                }
            });
            //If width is more than 943px dropdowns are displayed on hover

            $(".menu > ul > li").click(function () {
                if ($(window).width() <= 943) {
                    $(this).children("ul").fadeToggle(150);
                }
            });
            //If width is less or equal to 943px dropdowns are displayed on click (thanks Aman Jain from stackoverflow)

            $(".menu-mobile").click(function (e) {
                $(".menu > ul").toggleClass('show-on-mobile');
                e.preventDefault();
            });




        });

    </script>
    <?php
    /**
     * Top menu for store
     *
     * @see \Magento\Theme\Block\Html\Topmenu
     */
    ?>
    <nav class="navigation" role="navigation" >

        <div class="menu" id="om">
            <ul>
                <li class="level0 nav-1 first level-top ui-menu-item menu-logo" role="presentation">
                    <a href="<?php echo $homeUrl; ?>" class="level-top ui-corner-all" tabindex="-1" role="menuitem">
                        <span>
                            <img src="<?php /* @escapeNotVerified */ echo $logo->getLogoSrc() ?>"
                             alt="<?php /* @escapeNotVerified */ echo $logo->getLogoAlt() ?>"
                             <?php echo $logo->getLogoWidth() ? 'width="' . $logo->getLogoWidth() . '"' : '' ?>
                             <?php echo $logo->getLogoHeight() ? 'height="' . $logo->getLogoHeight() . '"' : '' ?>
                            />
                        </span>
                    </a>
                </li>
                <?php /* @escapeNotVerified */ echo $_menu2; ?>
                <li class="menu-dropdown-icon">
                    <a href="<?php echo $block->getUrl('about-us'); ?>" class="level-top" tabindex="-1" role="menuitem">
                        <span><?php echo __("The Brand"); ?></span>
                    </a>
                    <ul class="the-brand-submenu">
                        <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('brand_menu_block')->toHtml(); ?>
                    </ul>
                </li>
                <li>
                    <a href="<?php echo $block->getUrl('what-is-new'); ?>" class="level-top" tabindex="-1" role="menuitem">
                        <span><?php echo __("New Release"); ?></span>
                    </a>
                </li>
                <li>
                    <a href="<?php echo "#" ?>" class="level-top" tabindex="-1" role="menuitem">
                        <span><?php echo __("Blog"); ?></span>
                    </a>
                </li>
                <?php
                    $offerCategory = $objectManager->create('Magento\Catalog\Model\Category')->load(8);
                ?>
                <li>
                    <a href="<?php echo $block->getUrl('special-offer'); //echo $offerCategory->getUrl() ?>" class="level-top" tabindex="-1" role="menuitem">
                        <span><?php echo __("Offers"); ?></span>
                    </a>
                </li>
                <!-- Search block in menu -->
                <?php
                    $helper = $this->helper('Magento\Search\Helper\Data');
                ?>
                <li class="menu-search">
                    <?php
                        $searchBlock = $objectManager->get('\Magento\Framework\View\Element\Template');
                    ?>
                    <div class="block block-search">
                      <div class="block block-title"><strong><?php /* @escapeNotVerified */ echo __('Search'); ?></strong></div>
                      <div class="block block-content">
                          <form class="form minisearch" id="search_mini_form" action="<?php /* @escapeNotVerified */ echo $helper->getResultUrl() ?>" method="get">
                              <div class="field search">
                                  <label class="label" for="search" data-role="minisearch-label">
                                      <span><?php /* @escapeNotVerified */ echo __('Search'); ?></span>
                                  </label>
                                  <div class="control">
                                      <input id="search"
                                             data-mage-init='{"quickSearch":{
                                                  "formSelector":"#search_mini_form",
                                                  "url":"<?php /* @escapeNotVerified */ echo $searchBlock->getUrl('search/ajax/suggest', ['_secure' => $searchBlock->getRequest()->isSecure()]); ?>",
                                                  "destinationSelector":"#search_autocomplete"}
                                             }'
                                             type="text"
                                             name="<?php /* @escapeNotVerified */ echo $helper->getQueryParamName() ?>"
                                             value="<?php /* @escapeNotVerified */ echo $helper->getEscapedQueryText() ?>"
                                             class="input-text"
                                             maxlength="<?php /* @escapeNotVerified */ echo $helper->getMaxQueryLength();?>"
                                             role="combobox"
                                             aria-haspopup="false"
                                             aria-autocomplete="both"
                                             autocomplete="off"/>
                                      <div id="search_autocomplete" class="search-autocomplete"></div>
                                      <?php echo $searchBlock->getChildHtml() ?>
                                  </div>
                              </div>
                              <div class="actions">
                                  <button type="submit"
                                          title="<?php echo $searchBlock->escapeHtml(__('Search')) ?>"
                                          class="action search">
                                      <span><?php /* @escapeNotVerified */ echo __('Search'); ?></span>
                                  </button>
                              </div>
                          </form>
                      </div>
                    </div>
                </li>
            </ul>
        </div>
        <ul id="dm" data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
            <?php /* @escapeNotVerified */ echo $_menu; ?>
        </ul>
    </nav>

<?php else : ?>

    <nav class="navigation" role="navigation">
<?php /* @escapeNotVerified */ echo $_menu; ?>
    </nav>
<?php endif; ?>
