<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()): ?>
<div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()): ?>
        <div class="field qty">
            <div class="control">
                <span class="qty-btn qty-dec">-</span>
                <span class="qty-btn qty-inc">+</span>
                
                <input type="number"
                       name="qty"
                       id="qty"
                       maxlength="12"
                       value="<?php /* @escapeNotVerified */ echo $block->getProductDefaultQty() * 1 ?>"
                       title="<?php /* @escapeNotVerified */ echo __('Qty') ?>" class="input-text qty"
                       data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                       />
                
            </div>
        </div>
        <?php endif; ?>
        <div class="actions">
            <button type="submit"
                    title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
                    class="action primary tocart"
                    id="product-addtocart-button">
                <span><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
            </button>
            <?php echo $block->getChildHtml('', true) ?>
        </div>
    </div>
</div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }
</script>
<?php if (!$block->isRedirectToCartEnabled()) : ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "catalogAddToCart": {
                "bindSubmit": true
            }
        }
    }
</script>
<?php endif; ?>

<!-- Qty Manipulation Script -->
<script type="text/javascript">
    require([
        'jquery'
    ], function ($) {
        // This button will increment the value
        $('.box-tocart .field.qty .qty-inc').click(function(e){
            // Stop acting like a button
            e.preventDefault();
            // Get the field name
            fieldBox = $(this).closest('.control').find('.input-text.qty');
            // Get its current value
            var currentVal = parseInt(fieldBox.val());
            // If is not undefined
            if (!isNaN(currentVal)) {
                // Increment
                $(fieldBox).val(currentVal + 1);
            } else {
                // Otherwise put a 0 there
                $(fieldBox).val(0);
            }
        });

        // This button will decrement the value till 0
        $('.box-tocart .field.qty .qty-dec').click(function(e) {
            // Stop acting like a button
            e.preventDefault();
            // Get the field name
            fieldBox = $(this).closest('.control').find('.input-text.qty');
            // Get its current value
            var currentVal = parseInt(fieldBox.val());
            // If it isn't undefined or its greater than 0
            if (!isNaN(currentVal) && currentVal > 1) {
                // Decrement one
                fieldBox.val(currentVal - 1);
            } else {
                // Otherwise put a 0 there
                fieldBox.val(1);
            }
        });
    });
</script>