<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()): ?>
<div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()): ?>
        <div class="field qty">
            <div class="control">
                <span class="qty-btn qty-dec">-</span>
                <span class="qty-btn qty-inc">+</span>
                
                <input type="number"
                       name="qty"
                       id="qty"
                       maxlength="12"
                       value="<?php /* @escapeNotVerified */ echo $block->getProductDefaultQty() * 1 ?>"
                       title="<?php /* @escapeNotVerified */ echo __('Qty') ?>" class="input-text qty"
                       data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                       />
                
            </div>
        </div>
        <?php endif; ?>
        <div class="actions">
            <button type="submit"
                    title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
                    class="action primary tocart"
                    id="product-addtocart-button">
                <span><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
            </button>
            <?php echo $block->getChildHtml('', true) ?>
        </div>
    </div>
</div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }
</script>
<?php if (!$block->isRedirectToCartEnabled()) : ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "catalogAddToCart": {
                "bindSubmit": false
            }
        }
    }
</script>
<?php endif; ?>

<!-- Qty Manipulation Script -->
<script type="text/javascript">
    require([
        'jquery'
    ], function ($) {
        var value = parseInt($(".box-tocart .field.qty .input-text.qty").val());
        $(".box-tocart .field.qty .qty-inc").click(function(){
            // value = parseInt($(".box-tocart .field.qty .input-text.qty").val());
            value += 1;
            console.log(value);
            $(this).closest('.control').find('.input-text.qty').val(value);
            // $(".box-tocart .field.qty .input-text.qty").val(value);
        });
        $(document).on("click", ".box-tocart .field.qty .qty-inc", function(){
            if(($(".box-tocart .field.qty .input-text.qty").val() - 1) > 0)
                $(".box-tocart .field.qty .input-text.qty").val($(".box-tocart .field.qty .input-text.qty").val() - 1);
        });
    });
</script>