<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
use Magento\Catalog\Model\Product\ProductList\Toolbar;

?>
<div class="toolbar-sorter sorter">
    <label class="sorter-label" for="sorter"><?php /* @escapeNotVerified */ echo __('Sort By') ?>&nbsp;&nbsp;:&nbsp;&nbsp;</label>
    <div class="catalog-sorter sorter-options">
        <?php foreach ($block->getAvailableOrders() as $_key => $_order): ?>
            <div class="sorter-options">
                <?php
                    if ($block->isOrderCurrent($_key)) {
                        if ($block->getCurrentDirection() == 'desc'){
                            ?>
                            <a title="<?php echo __('Sort by %1 in ascending order', $_order) ?>" class="current ascending-sorter" href="?product_list_order=<?php echo $_key ?>&product_list_dir=asc"><?php echo $block->escapeHtml(__($_order)) ?></a>
                            <?php
                        } else{
                            ?>
                            <a title="<?php echo __('Sort by %1 in descending order', $_order) ?>" class="current descending-sorter" href="?product_list_order=<?php echo $_key ?>&product_list_dir=desc"><?php echo $block->escapeHtml(__($_order)) ?></a>
                            <?php
                        }
                    } else{
                        ?>
                        <a title="<?php echo __('Sort by %1 in descending order', $_order) ?>" class="descending-sorter" href="?product_list_order=<?php echo $_key ?>&product_list_dir=desc"><?php echo $block->escapeHtml(__($_order)) ?></a>
                        <?php
                    }
                ?>
            </div>
            <!-- <option value="<?php /* @escapeNotVerified */ echo $_key; ?>"
                <?php if ($block->isOrderCurrent($_key)): ?>
                    selected="selected"
                <?php endif; ?>
                >
                <?php echo $block->escapeHtml(__($_order)) ?>
            </option> -->
        <?php endforeach; ?>
    </div>
    <!-- <select id="sorter" data-role="sorter" class="sorter-options">
        <?php foreach ($block->getAvailableOrders() as $_key => $_order): ?>
            <option value="<?php /* @escapeNotVerified */ echo $_key; ?>"
                <?php if ($block->isOrderCurrent($_key)): ?>
                    selected="selected"
                <?php endif; ?>
                >
                <?php echo $block->escapeHtml(__($_order)) ?>
            </option>
        <?php endforeach; ?>
    </select>
    <?php if ($block->getCurrentDirection() == 'desc'): ?>
        <a title="<?php /* @escapeNotVerified */ echo __('Set Ascending Direction') ?>" href="#" class="action sorter-action sort-desc" data-role="direction-switcher" data-value="asc">
            <span><?php /* @escapeNotVerified */ echo __('Set Ascending Direction') ?></span>
        </a>
    <?php else: ?>
        <a title="<?php /* @escapeNotVerified */ echo __('Set Descending Direction') ?>" href="#" class="action sorter-action sort-asc" data-role="direction-switcher" data-value="desc">
            <span><?php /* @escapeNotVerified */ echo __('Set Descending Direction') ?></span>
        </a>
    <?php endif; ?> -->
</div>
