<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Wishlist\Block\Catalog\Product\View\Addto\Wishlist */
?>
<?php if ($block->isWishListAllowed()) : ?>
    <a href="#"
       class="action towishlist"
       data-post='<?php /* @escapeNotVerified */ echo $block->getWishlistParams(); ?>'
       data-action="add-to-wishlist"><span class="wishlist-icon"><img src="<?php echo $block->getViewFileUrl('images/catalog/product/fav/wishlist-active.png'); ?>"></span><span><?php /* @escapeNotVerified */ echo __('Add to Favourites') ?></span></a>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "body": {
            "addToWishlist": <?php /* @escapeNotVerified */ echo $block->getWishlistOptionsJson() ?>
        }
    }
</script>
